---
title: "Diamonds Price - LBB Regression Analysis"
author: "Yevonnael Andrew"
date: "2/18/2020"
output: 
  html_document:
    keep_md: true
  md_document:
    variant: markdown_github
---

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(skimr)
library(GGally)
library(corrr)
library(corrplot)
library(ggridges)
library(viridis)
library(hrbrthemes)
library(ggpubr)
library(moderndive)
library(olsrr)
library(MASS)
```

```{r, message=FALSE, warning=FALSE}
diamonds <- read_csv("diamonds.csv")
```

X : Length of the Diamond in mm.
Y : Width of the Diamond in mm.
Z : Height of the Diamond in mm.

```{r}
glimpse(diamonds)
```

```{r}
diamonds$cut <- as.factor(diamonds$cut)
diamonds$color <- as.factor(diamonds$color)
diamonds$clarity <- as.factor(diamonds$clarity)
```

```{r}
skim(diamonds)
```

```{r}
diamonds[, c(1, 9:11)] %>%
  filter(x == 0 | y == 0 | z == 0)
```

```{r}
diamonds <- diamonds[,-1] %>%
  filter(x != 0 | y != 0 | z != 0)
```

```{r}
smp_siz = floor(0.80*nrow(diamonds))
set.seed(123)
train_ind = sample(seq_len(nrow(diamonds)), size = smp_siz)
train = diamonds[train_ind,]
test = diamonds[-train_ind,] 
```

```{r, message=FALSE, warning=FALSE, fig.width=12, cache=TRUE}
ggpairs(train[4000:6000,])
```

```{r}
cor_mat <- cor(train[, -c(2:4)])
cor_mat
```

```{r}
corrplot(cor_mat, method="pie", type="lower", addCoef.col = "black")
```

```{r, fig.width=10, fig.height=10}
plot1 <- diamonds %>%
  ggplot(aes(x = x, y = price)) + 
  geom_point()
plot2 <- diamonds %>%
  ggplot(aes(x = y, y = price)) + 
  geom_point()

plot3 <- diamonds %>%
  ggplot(aes(x = z, y = price)) + 
  geom_point()
plot4 <- diamonds %>%
  ggplot(aes(x = carat, y = price)) + 
  geom_point()

plot5 <- diamonds %>%
  ggplot(aes(x = table, y = price)) +
  geom_point()
plot6 <- diamonds %>%
  ggplot(aes(x = depth, y = price)) + 
  geom_point()

ggarrange(plot1, plot2, plot3, plot4, plot5, plot6, ncol = 3, nrow = 3)
```

```{r, message=FALSE, waning=FALSE, fig.width=10, fig.height=10}
plot1 <- train %>%
  ggplot((aes(x = price, y = cut, fill = ..x..))) + 
  geom_density_ridges_gradient(scale = 2, rel_min_height = 0.01) +
  scale_fill_viridis(option = "A", direction = -1)
plot2 <- train %>%
  ggplot((aes(x = cut, y = price))) +
  geom_boxplot()

plot3 <- train %>%
  ggplot((aes(x = price, y = color, fill = ..x..))) + 
  geom_density_ridges_gradient(scale = 2, rel_min_height = 0.01) +
  scale_fill_viridis(option = "A", direction = -1)
plot4 <- train %>%
  ggplot((aes(x = color, y = price))) +
  geom_boxplot()

plot5 <- train %>%
  ggplot((aes(x = price, y = clarity, fill = ..x..))) + 
  geom_density_ridges_gradient(scale = 2, rel_min_height = 0.01) +
  scale_fill_viridis(option = "A", direction = -1)
plot6 <- train %>%
  ggplot((aes(x = clarity, y = price))) +
  geom_boxplot()

ggarrange(plot1, plot2, plot3, plot4, plot5, plot6, ncol = 2, nrow = 3)
```

```{r}
model_single <- lm(price ~ carat, data = train)
get_regression_summaries(model_single)
```

```{r}
model_full <- lm(price ~ ., data = train)
get_regression_summaries(model_full)
```

```{r}
model_bw <- step(model_full, direction = "backward", trace = FALSE)
model_fw <- step(model_single, scope = list(lower = model_single, upper = model_full), direction = "forward", trace = FALSE)
model_bo <- step(model_single, scope = list(lower = model_single, upper = model_full), direction = "both", trace = FALSE)
```

```{r, echo=FALSE}
paste("Step Backward: ", model_bw$call[[2]])
paste("Step Forward: ", model_fw$call[[2]])
paste("Step Both: ", model_bo$call[[2]])
```

```{r}
get_regression_summaries(model_bw)
```
```{r}
get_regression_summaries(model_fw)
```
```{r}
get_regression_summaries(model_bo)
```

```{r}
car::vif(model_bo)
```

```{r}
model_bo_vif <- lm(price ~ carat + cut + color + clarity + depth + table + z, data = train)
car::vif(model_bo_vif)
```

```{r}
model_bo_vif <- lm(price ~ carat + cut + color + clarity + depth + table, data = train)
car::vif(model_bo_vif)
```

```{r}
get_regression_summaries(model_bo_vif)
```

Testing the Normality Assumption
```{r, fig.width=8}
srs <- studres(model_bo_vif)
hist(srs, freq=FALSE, 
     main="Distribution of Studentized Residuals",
     breaks=100)
xfit<-seq(min(srs),max(srs),length=40) 
yfit<-dnorm(xfit) 
lines(xfit, yfit)
```

```{r}
ks.test(studres(model_bo_vif), dnorm(xfit))
```

```{r, fig.width=10}
par(mfrow = c(2,2))
plot(model_bo_vif)
```

## Normalization using bestNormalize()

Reference:
https://cran.r-project.org/web/packages/bestNormalize/vignettes/bestNormalize.html

```{r}
library(bestNormalize)
```

```{r}
par(mfrow=c(2, 4))
hist(train$carat)
hist(train$depth)
hist(train$table)
hist(train$price)
hist(train$x)
hist(train$y)
hist(train$z)
```

```{r}
train$caratBN <- orderNorm(train$carat)$x.t
train$depthBN <- orderNorm(train$depth)$x.t
train$tableBN <- orderNorm(train$table)$x.t
train$priceBN <- orderNorm(train$price)$x.t
train$xBN <- orderNorm(train$x)$x.t
train$yBN <- orderNorm(train$y)$x.t
train$zBN <- orderNorm(train$z)$x.t
```

```{r}
par(mfrow=c(2, 4))
hist(train$caratBN)
hist(train$depthBN)
hist(train$tableBN)
hist(train$priceBN)
hist(train$xBN)
hist(train$yBN)
hist(train$zBN)
```

```{r}
model_BN_full <- lm(priceBN ~ caratBN + depthBN + tableBN + xBN + yBN + zBN + cut + clarity + color, data = train)
summary(model_BN_full)
```

-----


```{r}
model_BN_none <- lm(priceBN ~ 1, data = train)
model_BN_bo <- step(model_BN_none, scope = list(lower = model_BN_none, upper = model_BN_full), direction = "both", trace = FALSE)
```

```{r}
summary(model_BN_bo)
```

Testing the Normality Assumption
```{r, fig.width=8}
srs <- studres(model_BN_bo)
hist(srs, freq=FALSE, 
     main="Distribution of Studentized Residuals",
     breaks=100)
xfit<-seq(min(srs),max(srs),length=40) 
yfit<-dnorm(xfit) 
lines(xfit, yfit)
```

```{r}
library(lmtest)
bptest(model_BN_bo)
```


```{r}
ks.test(studres(model_BN_bo), dnorm(xfit))
```

```{r}
hist(train$priceBN, breaks=1000)
```


## Outliers

```{r}
library(olsrr)
```

```{r}
cooksdplot <- ols_plot_cooksd_bar(model_BN_bo)
```

```{r}
data_cooksdplot <- cooksdplot$data
ind_outlier <- data_cooksdplot$color == "outlier"
train_clean <- train[ind_outlier == FALSE,]
train_outlier <- train[ind_outlier == TRUE,]
```

```{r}
model_BN_bo_clean <- lm(formula = priceBN ~ xBN + clarity + color + depthBN + zBN + 
    yBN + cut + tableBN + caratBN, data = train_clean)
```

```{r}
bptest(model_BN_bo_clean)
```


Testing the Normality Assumption
```{r, fig.width=8}
srs <- studres(model_BN_bo_clean)
hist(srs, freq=FALSE, 
     main="Distribution of Studentized Residuals",
     breaks=100)
xfit<-seq(min(srs),max(srs),length=100) 
yfit<-dnorm(xfit)
lines(xfit, yfit)
```

```{r}
ks.test(studres(model_BN_bo_clean), dnorm(xfit))
ks.test(model_BN_bo_clean$residuals, y = train_clean$priceBN)
```

```{r}
plot(model_BN_bo_clean)
```

```{r}
plot(model_BN_bo_clean$residuals, train_clean$priceBN)
```

